// client/src/App.jsx
import { useState, useEffect, useCallback } from 'react';
import TrailerList from './components/TrailerList';
import Header from './components/Header';
import ErrorMessage from './components/ErrorMessage';
import Loading from './components/Loading';
import StudioFilter from './components/StudioFilter';
import Pagination from './components/Pagination';
import './App.css';

const TRAILERS_PER_PAGE = 10;
const AUTOPLAY_INTERVAL = 30000; // 30 seconds per page

function App() {
  const [trailers, setTrailers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [selectedStudio, setSelectedStudio] = useState('all');
  const [currentPage, setCurrentPage] = useState(1);
  const [autoPlay, setAutoPlay] = useState(false);

  useEffect(() => {
    fetchTrailers();
  }, []);

  // Auto-play functionality
  useEffect(() => {
    if (!autoPlay) return;

    const filteredTrailers = getFilteredTrailers();
    const totalPages = Math.ceil(filteredTrailers.length / TRAILERS_PER_PAGE);

    const timer = setInterval(() => {
      setCurrentPage(prev => {
        if (prev >= totalPages) return 1;
        return prev + 1;
      });
    }, AUTOPLAY_INTERVAL);

    return () => clearInterval(timer);
  }, [autoPlay, selectedStudio, trailers]);

  const fetchTrailers = async () => {
    try {
      setLoading(true);
      setError(null);

      const response = await fetch('/api');

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }

      const data = await response.json();

      if (data.apiValid === false) {
        throw new Error(data.error?.message || 'API validation failed');
      }

      setTrailers(data);
    } catch (err) {
      console.error('Error fetching trailers:', err);
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleRefresh = () => {
    fetchTrailers();
  };

  const getFilteredTrailers = useCallback(() => {
    if (selectedStudio === 'all') {
      return trailers;
    }
    return trailers.filter(t => t.channel === selectedStudio);
  }, [trailers, selectedStudio]);

  const getStudioCounts = useCallback(() => {
    const counts = trailers.reduce((acc, trailer) => {
      acc[trailer.channel] = (acc[trailer.channel] || 0) + 1;
      return acc;
    }, {});

    const studios = Object.keys(counts).map(name => ({
      name,
      count: counts[name]
    }));

    studios.unshift({ name: 'all', count: trailers.length });
    return studios;
  }, [trailers]);

  const handleFilterChange = (studio) => {
    setSelectedStudio(studio);
    setCurrentPage(1);
    setAutoPlay(false);
  };

  const handlePageChange = (page) => {
    setCurrentPage(page);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleAutoPlayToggle = () => {
    setAutoPlay(!autoPlay);
    if (!autoPlay) {
      setCurrentPage(1);
    }
  };

  const filteredTrailers = getFilteredTrailers();
  const totalPages = Math.ceil(filteredTrailers.length / TRAILERS_PER_PAGE);
  const startIndex = (currentPage - 1) * TRAILERS_PER_PAGE;
  const paginatedTrailers = filteredTrailers.slice(startIndex, startIndex + TRAILERS_PER_PAGE);

  return (
    <div className="app">
      <Header onRefresh={handleRefresh} loading={loading} />

      {!loading && !error && trailers.length > 0 && (
        <StudioFilter
          studios={getStudioCounts()}
          selectedStudio={selectedStudio}
          onFilterChange={handleFilterChange}
        />
      )}

      <main className="main-content">
        {loading && <Loading />}

        {error && !loading && (
          <ErrorMessage message={error} onRetry={handleRefresh} />
        )}

        {!loading && !error && trailers.length === 0 && (
          <div className="no-trailers">
            <h2>No Trailers Found</h2>
            <p>Check back soon for the latest movie trailers!</p>
          </div>
        )}

        {!loading && !error && filteredTrailers.length === 0 && trailers.length > 0 && (
          <div className="no-trailers">
            <h2>No Trailers from {selectedStudio}</h2>
            <p>Try selecting a different studio or view all trailers.</p>
          </div>
        )}

        {!loading && !error && paginatedTrailers.length > 0 && (
          <>
            <div className="trailer-showcase">
              <TrailerList trailers={paginatedTrailers} />
            </div>

            <Pagination
              currentPage={currentPage}
              totalPages={totalPages}
              onPageChange={handlePageChange}
              autoPlay={autoPlay}
              onAutoPlayToggle={handleAutoPlayToggle}
            />
          </>
        )}
      </main>

      <footer className="footer">
        <div className="footer-content">
          <p className="footer-stats">
            {filteredTrailers.length} {selectedStudio === 'all' ? 'total' : selectedStudio} trailers
            {selectedStudio === 'all' && ` from ${getStudioCounts().length - 1} studios`}
          </p>
          <p className="footer-tagline">Powered by YouTube • Updated every 5 minutes</p>
        </div>
      </footer>
    </div>
  );
}

export default App;

// client/src/App.vue
<template>
  <div class="app">
    <Header :onRefresh="handleRefresh" :loading="store.loading" />

    <!-- Floating Filter - Top Right -->
    <div class="floating-filter-container">
      <StudioFilter
        v-if="!store.loading && !store.error && store.trailers.length > 0"
        :studios="store.studioCounts"
        :selectedStudio="store.selectedStudio"
        :onFilterChange="handleFilterChange"
      />
    </div>

    <main class="main-content">
      <Loading v-if="store.loading" />

      <ErrorMessage
        v-if="store.error && !store.loading"
        :message="store.error"
        :onRetry="handleRefresh"
      />

      <div v-if="!store.loading && !store.error && store.trailers.length === 0" class="no-trailers">
        <h2>No Trailers Found</h2>
        <p>Check back soon for the latest movie trailers!</p>
      </div>

      <div
        v-if="!store.loading && !store.error && store.filteredTrailers.length === 0 && store.trailers.length > 0"
        class="no-trailers"
      >
        <h2>No Trailers from {{ store.selectedStudio }}</h2>
        <p>Try selecting a different studio or view all trailers.</p>
      </div>

      <template v-if="!store.loading && !store.error && store.paginatedTrailers.length > 0">
        <div class="trailer-showcase">
          <TrailerList :trailers="store.paginatedTrailers" @play="handlePlayVideo" />
        </div>

        <Pagination
          :currentPage="store.currentPage"
          :totalPages="store.totalPages"
          :onPageChange="handlePageChange"
        />
      </template>
    </main>

    <footer class="footer">
      <div class="footer-content">
        <p class="footer-stats">
          {{ store.filteredTrailers.length }} {{ store.selectedStudio === 'all' ? 'total' : store.selectedStudio }} trailers
          <template v-if="store.selectedStudio === 'all'">
            from {{ store.studioCounts.length - 1 }} studios
          </template>
        </p>
        <p class="footer-tagline">Powered by YouTube • Updated every 5 minutes</p>
      </div>
    </footer>

    <!-- Video Modal -->
    <VideoModal :isOpen="isModalOpen" :trailer="selectedTrailer" @close="closeModal" />
  </div>
</template>

<script setup>
import { ref, onMounted, defineAsyncComponent } from 'vue';
import { useTrailerStore } from './stores/trailerStore';
import TrailerList from './components/TrailerList.vue';
import Header from './components/Header.vue';
import ErrorMessage from './components/ErrorMessage.vue';
import Loading from './components/Loading.vue';
import StudioFilter from './components/StudioFilter.vue';
import Pagination from './components/Pagination.vue';

// OPTIMIZATION: Lazy load VideoModal - only loaded when user clicks a trailer
const VideoModal = defineAsyncComponent(() =>
  import('./components/VideoModal.vue')
);

const store = useTrailerStore();

const isModalOpen = ref(false);
const selectedTrailer = ref(null);

onMounted(() => {
  store.fetchTrailers();
});

const handleRefresh = () => {
  store.fetchTrailers();
};

const handleFilterChange = (studio) => {
  store.setSelectedStudio(studio);
};

const handlePageChange = (page) => {
  store.setCurrentPage(page);
  window.scrollTo({ top: 0, behavior: 'smooth' });
};

const handlePlayVideo = (trailer) => {
  selectedTrailer.value = trailer;
  isModalOpen.value = true;
};

const closeModal = () => {
  isModalOpen.value = false;
  setTimeout(() => {
    selectedTrailer.value = null;
  }, 300); // Wait for modal animation to complete
};
</script>

<style src="./App.css"></style>

<style scoped>
.floating-filter-container {
  position: fixed;
  top: 6rem;
  right: 2rem;
  z-index: 100;
}

@media (max-width: 768px) {
  .floating-filter-container {
    top: 5rem;
    right: 1rem;
  }
}
</style>
