// client/src/components/ErrorMessage.vue
<template>
  <div class="error-message">
    <h2>Oops! Something went wrong</h2>
    <p>{{ message }}</p>
    <button @click="onRetry" class="retry-button">
      Try Again
    </button>
  </div>
</template>

<script setup>
defineProps({
  message: {
    type: String,
    required: true
  },
  onRetry: {
    type: Function,
    required: true
  }
});
</script>

// client/src/components/ErrorMessage.jsx
import PropTypes from 'prop-types';

function ErrorMessage({ message, onRetry }) {
  return (
    <div className="error-message">
      <h2>Oops! Something went wrong</h2>
      <p>{message}</p>
      <button onClick={onRetry} className="retry-button">
        Try Again
      </button>
    </div>
  );
}

ErrorMessage.propTypes = {
  message: PropTypes.string.isRequired,
  onRetry: PropTypes.func.isRequired
};

export default ErrorMessage;
